language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t gjangra/docker-react -f Dokcerfile.dev .

script:
  - docker run -e CI=true gjangra/docker-react npm run test -- --coverage